### PR TITLE
Update elasticsearch/kibana image tags

### PR DESCRIPTION
**Pull request by celanthe**
This PR updates the elasticsearch and kibana image tags from 6.8.5 to 7.10.1. 

Ref: #114 #115

### CODE REVIEW

**Review by falko — CHANGES_REQUESTED** [review]
According to the docs, [Zeebe requires Elasticsearch 7.12.x](https://docs.camunda.io/docs/reference/supported-environments/#zeebe).

[Docker Hub](https://hub.docker.com/_/elasticsearch?tab=tags&page=1&ordering=last_updated) has 7.12.1 as the latest 7.12.x version but also already 7.13.4. I'm not sure if Zeebe needs exactly 7.12.x or a newer 7.13.x is also fine. @Zelldon @npepinpe

**Comment by celanthe** [comment]
Oh awesome, thank you @falko! I'll go ahead and update this again to 7.12

**Review by falko — COMMENTED** [review]
LGTM

**Review by menski — APPROVED** [review]
Zeebe 1.0.x needs elasticsearch 7.12.1 so this change is :ok_hand:

**Pull request merged**
